services:
  - type: web
    name: barcode-generator-2
    runtime: node
    buildCommand: npm install
    startCommand: node app.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_USERNAME
        sync: false
      - key: MONGO_PASSWORD
        sync: false
      - key: MONGO_CLUSTER
        sync: false
      - key: MONGO_DB_NAME
        value: qrmanager
    healthCheckPath: /health
    scaling:
      minInstances: 1
      maxInstances: 1
